<a href="https://colab.research.google.com/github/timhapp/ai_lotto_picker/blob/main/lottoPicker_scikit_PB_WeatherData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import a bunch of libraries

In [ ]:
#Importing Libraries
!pip install -q sodapy
from sodapy import Socrata

import requests
import json
#import math

import datetime
from datetime import timedelta
from datetime import datetime
import pytz

import numpy as np
import pandas as pd

import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn import linear_model
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPRegressor

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
#from sklearn.externals import joblib ## depreciated
from sklearn.impute import SimpleImputer

The scikit-learn version is 1.0.2.


In [ ]:
!pip install awsebcli
!pip install awscli --ignore-installed six
!pip install botocore==1.29 --upgrade
!pip install boto3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached botocore-1.23.54-py3-none-any.whl (8.5 MB)
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: jmespath
    Found existing installation: jmespath 1.0.1
    Uninstalling jmespath-1.0.1:
      Successfully uninstalled jmespath-1.0.1
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.4
    Uninstalling colorama-0.4.4:
      Successfully uninstalled colorama-0.4.4
  Attempting uninstall: botocore
    Found existing installation: botocore 1.27.57
    Uninstalling botocore-1.27.57:
      Successfully uninstalled botocore-1.27.57
ERROR: pip's dependency resolver does no

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached awscli-1.25.58-py3-none-any.whl (3.9 MB)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
  Using cached PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
  Using cached botocore-1.27.57-py3-none-any.whl (9.1 MB)
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
  Using cached s3transfer-0.6.0-py3-none-any.whl (79 kB)
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement botocore==1.29 (from versions: 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.39.0, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 0.54.0, 0.55.0, 0.56.0, 0.57.0, 0.58.0, 0.59.0, 0.60.0, 0.61.0, 0.62.0, 0.63.0, 0.64.0, 0.65.0, 0.66.0, 0.67.0, 0.68.0, 0.69.0, 0.70.0, 0.71.0, 0.72.0, 0.73.0, 0.74.0, 0.75.0, 0.76.0, 0.77.0, 0.78.0, 0.79.0, 0.80.0, 0.81.0, 0.82.0, 0.83.0, 0.84.0, 0.85.0, 0.86.0, 0.87.0, 0.88.0, 0.89.0, 0.90.0, 0.91.0, 0.92.0, 0.93.0, 0.94.0,

In [ ]:
import boto3
from boto3.dynamodb.conditions import Key, Attr

In [ ]:
dynamodb = boto3.resource('dynamodb',aws_access_key_id='AKIAJQE6ASOMCWSDQZ4Q', aws_secret_access_key='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', region_name='us-east-1')

# Write to Weather - PB

In [ ]:
LuckyWeatherNumbers = dynamodb.Table('LuckyWeatherNumbers')
print(LuckyWeatherNumbers.creation_date_time)

2018-11-14 06:15:53.690000+00:00


In [ ]:
# Powerball lotto (https://data.ny.gov/resource/d6yy-54nr.json)
client = Socrata("data.ny.gov", None)
results = client.get("8vkr-v8vh", limit=5, order="draw_date DESC", offset=0)
# weather
url = 'https://api.weatherstem.com/api'
values = {
    'api_key':'fso3dec6',
    'stations':['fsus@leon.weatherstem.com','fsu@leon.weatherstem.com'],
    'from': '2018-11-11 22:59:00',
    'to': '2018-11-11 23:00:00',
    'sensors':["Barometer", "Dewpoint", "Heat Index", "Hygrometer", "Thermometer"]
}

for draw in results:
    date_obj = datetime.strptime(draw['draw_date'], '%Y-%m-%dT%H:%M:%S.%f')
    values['from'] = str(datetime.date(date_obj)) + " 22:59:00"
    values['to'] = str(datetime.date(date_obj)) + " 23:01:00"
    response = requests.post(url, data=json.dumps(values))
    dayWeatherData = json.loads(response.text)
    number_POS = draw['winning_numbers'].split()
    try:
        DBentry = LuckyWeatherNumbers.put_item(
        Item = {
            'draw_date': str(datetime.date(date_obj)),
            'night': str(datetime.date(date_obj).weekday()),
            'POS1': number_POS[0],
            'POS2': number_POS[1],
            'POS3': number_POS[2],
            'POS4': number_POS[3],
            'POS5': number_POS[4],
            'PWRB': number_POS[5],
            'Station': dayWeatherData[0]['station']['handle'],
            'Barometer': dayWeatherData[0]["records"][1][1],
            'Dewpoint': dayWeatherData[0]["records"][1][2],
            'Heat_Index': dayWeatherData[0]["records"][1][3],
            'Hygrometer': dayWeatherData[0]["records"][1][4],
            'Thermometer': dayWeatherData[0]["records"][1][5]
            }
        )
        print(str(datetime.date(date_obj)), draw['winning_numbers'], DBentry['ResponseMetadata']['RequestId'])
    except:
        print(str(datetime.date(date_obj)), draw['winning_numbers'])
        print(dayWeatherData[1]["records"])
        try:
            DBentry = LuckyWeatherNumbers.put_item(
            Item = {
                'draw_date': str(datetime.date(date_obj)),
                'night': str(datetime.date(date_obj).weekday()),
                'POS1': number_POS[0],
                'POS2': number_POS[1],
                'POS3': number_POS[2],
                'POS4': number_POS[3],
                'POS5': number_POS[4],
                'PWRB': number_POS[5],
                'Station': dayWeatherData[1]['station']['handle'],
                'Barometer': dayWeatherData[1]["records"][1][1],
                'Dewpoint': dayWeatherData[1]["records"][1][2],
                'Heat_Index': dayWeatherData[1]["records"][1][3],
                'Hygrometer': dayWeatherData[1]["records"][1][4],
                'Thermometer': dayWeatherData[1]["records"][1][5]
                }
            )
            print(str(datetime.date(date_obj)), draw['winning_numbers'], DBentry['ResponseMetadata']['RequestId'])
        except:
            print(str(datetime.date(date_obj)), draw['winning_numbers'])
            continue
        continue

2022-08-22 12 27 34 55 67 09 FNU8B7A74V7HR13KT7I80UN7H3VV4KQNSO5AEMVJF66Q9ASUAAJG
2022-08-20 05 09 11 16 66 07 GLPB5N14Q2D1FQNLMVS4JE9VURVV4KQNSO5AEMVJF66Q9ASUAAJG
2022-08-17 23 28 41 50 55 24 DF09L3TJP9LU3T9P38LR89DSVJVV4KQNSO5AEMVJF66Q9ASUAAJG
2022-08-15 20 24 47 50 63 05 4ONESG99VPJV8J43CK4OAHIS1NVV4KQNSO5AEMVJF66Q9ASUAAJG
2022-08-13 19 24 35 43 62 02 CHMJHJQVQJ2T0MRC69UOKEKOA7VV4KQNSO5AEMVJF66Q9ASUAAJG


# predictionScore
Score the results on triangular numbers.

In [ ]:
def predictionScore(prediction, sample):
    sample = list(sample)
    c = 0
    for p in prediction:
        if p in sample:
            c += 1
            sample.remove(p)
    if c > 0:
        #Triangular number
        return ((c**2)+c)/(2)
    else:
        return c

# Get data for next draw day
* Next draw day for Powerball
* Weather for the next draw date

In [ ]:
utc=pytz.utc
nextdraw_date = datetime.today()
print(nextdraw_date)

while nextdraw_date.weekday() != 0:
    if nextdraw_date.weekday() == 2:
        break
    if nextdraw_date.weekday() == 5:
        break
    else:
        nextdraw_date += timedelta(1)

# manually set date
#nextdraw_date = nextdraw_date.replace(year=2022, month=8, day=8)

nextdraw_date = nextdraw_date.replace(hour=22, minute=0)
nextdraw_date_utcepoch = int(nextdraw_date.astimezone(utc).timestamp())

print(nextdraw_date_utcepoch, nextdraw_date.strftime("%Y-%m-%d %H:%M:%S"), nextdraw_date.weekday())

nextDrawResults = []

2022-08-23 15:47:19.754513
1661378419 2022-08-24 22:00:19 2


In [ ]:
## Get weather data for next draw date
# 250 Marriott Dr | Tallahassee, FL 32301
# lat: 30.439489
# lon: -84.264712
# hPa / 33.863886666667 = inHg (barometer)

url = "https://api.darksky.net/forecast/f6a6de11a8a5f55d5036ab0c6ed8650b/30.439489,-84.264712," + str(nextdraw_date_utcepoch) + "?exclude=hourly,minutely,daily,alerts,flags"
response = requests.get(url)
dayWeatherData = json.loads(response.text)
#print(dayWeatherData['currently'])

nextdraw_barometer = round((dayWeatherData['currently']['pressure'] / 33.863886666667), 3)
nextdraw_dewPoint = dayWeatherData['currently']['dewPoint']
nextdraw_apparentTemperature = dayWeatherData['currently']['apparentTemperature']
nextdraw_humidity = int(dayWeatherData['currently']['humidity']*100)
nextdraw_temperature = dayWeatherData['currently']['temperature']

#print( nextdraw_barometer, nextdraw_dewPoint, nextdraw_apparentTemperature, nextdraw_humidity, nextdraw_temperature, nextdraw_date.weekday())
nextdraw_set = [nextdraw_barometer, nextdraw_dewPoint, nextdraw_apparentTemperature, nextdraw_humidity, nextdraw_temperature, nextdraw_date.weekday()]
print(nextdraw_set)

[29.97, 74.8, 86.84, 81, 81.06, 2]


# Weather predictions
What if the weather affected the way the numbers dropped? Well, if i did, this script should find it.
*   Grab all the historic data
*   Split up the data

In [ ]:
table = dynamodb.Table('LuckyWeatherNumbers')
#print(table.creation_date_time)

# grab all the records...
response = table.scan(
    FilterExpression=Attr('night').gt('1') & Attr('PWRB').gt('0'),
    ProjectionExpression='draw_date, POS1, POS2, POS3, POS4, POS5, PWRB, Barometer, Dewpoint, Heat_Index, Hygrometer, Thermometer, night',
    Limit=1040
)
# put them in a dataframe
df_w = pd.DataFrame(response['Items'])

# make everything numeric
for column in df_w:
    # set all to numeric
    df_w[column] = pd.to_numeric(df_w[column], errors='coerce')


# re-sort the columns
df_w = df_w[['POS1', 'POS2', 'POS3', 'POS4', 'POS5', 'PWRB', 'Barometer', 'Dewpoint', 'Heat_Index', 'Hygrometer', 'Thermometer', 'night']]

#print('Shape of the dataset: ' + str(df_w.shape))
df_w.head()


POS1  POS2  POS3  POS4  POS5  PWRB  Barometer  Dewpoint  Heat_Index  \
0     7    42    49    62    69    23     30.072      55.0        57.0   
1    40    43    48    59    69    19     30.234      57.0        61.0   
2    12    17    30    45    62     5     29.917      67.0        75.0   
3    11    13    55    56    69     4     30.144      63.0        77.0   
4    10    31    41    63    67     5     29.974      71.0        83.0   

   Hygrometer  Thermometer  night  
0          95         56.5      2  
1          86         61.0      5  
2          80         73.6      5  
3          66         75.2      2  
4          76         79.3      5

In [ ]:
# Split the data into independent and dependent variables
X = df_w.iloc[:,6:12].values
y = df_w.iloc[:,0:6].values
print('The independent features set: ')
print(X[:5,:])
print('The dependent variable: ')
print(y[:5])

The independent features set: 
[[30.072 55.    57.    95.    56.5    2.   ]
 [30.234 57.    61.    86.    61.     5.   ]
 [29.917 67.    75.    80.    73.6    5.   ]
 [30.144 63.    77.    66.    75.2    2.   ]
 [29.974 71.    83.    76.    79.3    5.   ]]
The dependent variable: 
[[ 7 42 49 62 69 23]
 [40 43 48 59 69 19]
 [12 17 30 45 62  5]
 [11 13 55 56 69  4]
 [10 31 41 63 67  5]]


In [ ]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)#, random_state = 69)
print(X_train[:3,:])
#y_train = y_train.reshape(-1,1)
print(y_train[:3])

# Feature Scaling
scaler = StandardScaler()
X_fit_train = scaler.fit_transform(X_train)
X_fit_test = scaler.transform(X_test)
print('Scaled:')
#X_fit_train = X_fit_train.reshape(-1,1)
print(X_fit_train[:3,:])

X_fit = scaler.fit_transform(X)
print('X Scaled:')
#X_fit = X_fit.reshape(-1,1)
print(X_fit[:3,:])

[[30.048 67.    71.    94.    68.6    5.   ]
 [29.972 72.    81.    83.    77.9    2.   ]
 [29.97  61.2   65.7   88.    64.8    5.   ]]
[[15 33 43 59 60  8]
 [ 4 22 24 31 33 10]
 [ 8 12 18 44 51 18]]
Scaled:
[[ 0.15178598  0.42627454  0.06710356  1.12776067  0.05010003  0.99646017]
 [-0.38506972  0.79597336  0.78977699  0.25969278  0.83829647 -1.00355241]
 [-0.3991975  -0.00257609 -0.31591336  0.65426909 -0.27195873  0.99646017]]
X Scaled:
[[ 0.30856102 -0.45421854 -0.93565847  1.21450431 -0.96858386 -0.99717114]
 [ 1.46340052 -0.30580618 -0.64786703  0.50411488 -0.58710603  1.00283689]
 [-0.79637802  0.4362556   0.359403    0.03052193  0.4810319   1.00283689]]


# Random Forest - entropy

In [ ]:
winningScore = 0
winningState = 0
RFcriterion = "entropy"

irandom_state = 1
while irandom_state <= 104:
    # Fitting Random Forest Classification to the Training set
    RFclassifier = RandomForestClassifier(n_estimators=irandom_state, criterion=RFcriterion, random_state=irandom_state)
    RFclassifier.fit(X_fit_train, y_train)
    #print (RFclassifier)

    # Compare the Test set results for Random Forest Classification
    y_pred = RFclassifier.predict(X_fit_test)
    
    print('----- ' + str(irandom_state) + ' ------')
    accuracyScore = 0
    totalMatchScore = 0
    for index, pred in enumerate(y_pred):
        accuracy = accuracy_score(y_test[index], pred)
        accuracyScore += accuracy
        comparePOS = list(set(pred[:5]) & set(y_test[index][:5]))
        comparePWB = list(set(pred[5:]) & set(y_test[index][5:]))
        matchScore = predictionScore(pred[:5], y_test[index][:5]) + (predictionScore(pred[5:], y_test[index][5:])*6)
        if matchScore >= 6:
            totalMatchScore += matchScore
            print(pred, y_test[index], comparePOS, comparePWB, str(int(matchScore)))
        # Find the winner!
        if totalMatchScore >= winningScore:
            winningScore = totalMatchScore
            winningState = irandom_state
    print('-----> Accuracy: ' + str(round(accuracyScore,4)) + ' | Match Score: ' + str(int(totalMatchScore)) + ' <------')

    irandom_state += 1

----- 1 ------
[ 4  9 17 27 38 18] [ 4 26 32 55 64 18] [4] [18] 7
[17 40 41 46 69  6] [ 9 10 32 42 55  6] [] [6] 6
[ 4 17 26 32 49 10] [ 8 25 34 38 41 10] [] [10] 6
[17 19 26 61 62 15] [ 1 15 17 46 66 15] [17] [15] 7
[23 55 59 64 69 13] [ 8 23 37 52 63 13] [23] [13] 7
-----> Accuracy: 4.6667 | Match Score: 33 <------
----- 2 ------
[ 4 17 55 58 64 12] [20 33 36 47 52 12] [] [12] 6
[ 3 20 32 37 58 12] [19 37 48 61 63 12] [37] [12] 7
[ 4  7 15 41 44  4] [ 7 15 20 29 41 22] [41, 15, 7] [] 6
[ 5 25 26 36 65  4] [ 8 31 39 40 43  4] [] [4] 6
[ 1 19 31 43 52  6] [ 4 33 39 46 60  6] [] [6] 6
[ 5  9 11 33 59 21] [11 33 44 59 67  8] [33, 11, 59] [] 6
-----> Accuracy: 4.5 | Match Score: 37 <------
----- 3 ------
[ 1  3 44 19 57 11] [ 9 21 56 57 66 11] [57] [11] 7
[ 3 15 29 54 57 10] [19 43 47 60 68 10] [] [10] 6
[ 9 26 37 39 58 12] [ 8 12 42 46 56 12] [] [12] 6
[ 3 12 20 21 33  1] [ 4 18 21 26 38  1] [21] [1] 7
[ 4 14 23 27 56  4] [ 6  7 16 23 26  4] [23] [4] 7
[ 7 15 31 34 36  8] [15 27 44 59 63

In [ ]:
print('-----> Winner is ' + str(int(winningState)) + ' with ' + str(int(winningScore)) + ' <------')
# Fitting Random Forest Classification to the Training set
RFclassifier = RandomForestClassifier(n_estimators=int(winningState), criterion=RFcriterion, random_state=int(winningState))
RFclassifier.fit(X_fit, y)

# Predicting the next draw set results
nextdraw_pred = RFclassifier.predict([nextdraw_set])
print(nextdraw_pred[0], nextdraw_set)

nextDrawResults.append([{"numbers":list(map(int, nextdraw_pred[0]))},{"score":int(winningScore)},{"class":"weather - RandomForestClassifier - E"}])

-----> Winner is 35 with 80 <------
[ 3 17 49 58 68  8] [29.97, 74.8, 86.84, 81, 81.06, 2]


# Random Forest - gini

In [ ]:
winningScore = 0
winningState = 0
RFcriterion = "gini"

irandom_state = 1
while irandom_state <= 104:
    # Fitting Random Forest Classification to the Training set
    RFclassifier = RandomForestClassifier(n_estimators=irandom_state, criterion=RFcriterion, random_state=irandom_state)
    RFclassifier.fit(X_fit_train, y_train)
    #print (RFclassifier)

    # Compare the Test set results for Random Forest Classification
    y_pred = RFclassifier.predict(X_fit_test)
    
    print('----- ' + str(irandom_state) + ' ------')
    accuracyScore = 0
    totalMatchScore = 0
    for index, pred in enumerate(y_pred):
        accuracy = accuracy_score(y_test[index], pred)
        accuracyScore += accuracy
        comparePOS = list(set(pred[:5]) & set(y_test[index][:5]))
        comparePWB = list(set(pred[5:]) & set(y_test[index][5:]))
        matchScore = predictionScore(pred[:5], y_test[index][:5]) + (predictionScore(pred[5:], y_test[index][5:])*6)
        if matchScore >= 6:
            totalMatchScore += matchScore
            print(pred, y_test[index], comparePOS, comparePWB, str(int(matchScore)))
        # Find the winner!
        if totalMatchScore >= winningScore:
            winningScore = totalMatchScore
            winningState = irandom_state
    print('-----> Accuracy: ' + str(round(accuracyScore,4)) + ' | Match Score: ' + str(int(totalMatchScore)) + ' <------')

    irandom_state += 1

----- 1 ------
[ 8 17 49 52 59  1] [17 18 49 59 66  9] [17, 59, 49] [] 6
[19 28 43 67 69  7] [19 28 41 42 51  7] [19, 28] [7] 9
[ 1  2  7 52 61  4] [11 14 31 47 48  4] [] [4] 6
[24 61 63 64 69 18] [ 5 21 36 61 62 18] [61] [18] 7
[ 7 15 31 34 36  8] [15 27 44 59 63  8] [15] [8] 7
-----> Accuracy: 5.8333 | Match Score: 35 <------
----- 2 ------
[ 4  9 17 27 38 18] [ 4 26 32 55 64 18] [4] [18] 7
[17 28 41 46 56  6] [ 9 10 32 42 55  6] [] [6] 6
[11 22 28 45 50  4] [ 8 31 39 40 43  4] [] [4] 6
[ 7 15 31 34 36  8] [15 27 44 59 63  8] [15] [8] 7
[ 8 12 20 21 32 10] [ 5  6 15 29 42 10] [] [10] 6
-----> Accuracy: 4.6667 | Match Score: 32 <------
----- 3 ------
[ 8 20 22 43 64  3] [22 39 43 62 64  7] [64, 43, 22] [] 6
[ 3  7 15 41 44 10] [ 7 15 20 29 41 22] [41, 15, 7] [] 6
[14 20 21 42 48  4] [11 13 55 56 69  4] [] [4] 6
[ 8 12 18 44 51 12] [ 8 12 42 46 56 12] [8, 12] [12] 9
[10 13 30 51 53  1] [ 4 18 21 26 38  1] [] [1] 6
-----> Accuracy: 4.6667 | Match Score: 33 <------
----- 4 ------
[17 11 

In [ ]:
print('-----> Winner is ' + str(int(winningState)) + ' with ' + str(int(winningScore)) + ' <------')
# Fitting Random Forest Classification to the Training set
RFclassifier = RandomForestClassifier(n_estimators=int(winningState), criterion=RFcriterion, random_state=int(winningState))
RFclassifier.fit(X_fit, y)

# Predicting the next draw set results
nextdraw_pred = RFclassifier.predict([nextdraw_set])
print(nextdraw_pred[0], nextdraw_set)

nextDrawResults.append([{"numbers":list(map(int, nextdraw_pred[0]))},{"score":int(winningScore)},{"class":"weather - RandomForestClassifier - G"}])

-----> Winner is 25 with 74 <------
[ 3 25 35 58 68 10] [29.97, 74.8, 86.84, 81, 81.06, 2]


# KNN Classifier - uniform

In [ ]:
winningScore = 0
winningState = 0

in_neighbors = 1
while in_neighbors <= 154:
    # Fitting KNN
    KNNWeights = "uniform" # weights{"uniform", "distance"}
    KNNAlgorithm = "auto" # algorithm{"auto", "ball_tree", "kd_tree", "brute"}
    neigh = KNeighborsClassifier(weights=KNNWeights, algorithm=KNNAlgorithm, n_neighbors=in_neighbors)
    neigh.fit(X_fit_train, y_train)

    # Predicting the Test set results
    y_n_pred = neigh.predict(X_fit_test)
    
    print('----- ' + str(in_neighbors) + ' ------')
    accuracyScore = 0
    totalMatchScore = 0
    for index, pred in enumerate(y_n_pred):
        accuracy = accuracy_score(y_test[index], pred)
        accuracyScore += accuracy
        comparePOS = list(set(pred[:5]) & set(y_test[index][:5]))
        comparePWB = list(set(pred[5:]) & set(y_test[index][5:]))
        matchScore = predictionScore(pred[:5], y_test[index][:5]) + (predictionScore(pred[5:], y_test[index][5:])*6)
        if matchScore >= 6:
            totalMatchScore += matchScore
            print(pred, y_test[index], comparePOS, comparePWB, matchScore)
        # Find the winner!
        if totalMatchScore >= winningScore:
            winningScore = totalMatchScore
            winningState = in_neighbors
    print('-----> Accuracy: ' + str(round(accuracyScore,4)) + ' | Match Score: ' + str(totalMatchScore) + ' <------')

    in_neighbors += 1

----- 1 ------
[ 7 15 18 32 45 20] [10 30 51 57 63 20] [] [20] 6.0
[23 25 39 54 67 11] [ 4 39 48 50 51 11] [39] [11] 7.0
[19 28 43 67 69  7] [19 28 41 42 51  7] [19, 28] [7] 9.0
[ 3 43 45 61 65 14] [19 25 43 46 48 14] [43] [14] 7.0
[24 61 63 64 69 18] [ 5 21 36 61 62 18] [61] [18] 7.0
[ 1 15 21 32 46  1] [ 7 10 16 46 56  1] [46] [1] 7.0
[17 54 56 63 69 20] [ 3  7  9 31 33 20] [] [20] 6.0
-----> Accuracy: 3.8333 | Match Score: 49.0 <------
----- 2 ------
[ 7 15 18 32 45 20] [10 30 51 57 63 20] [] [20] 6.0
[ 2 25 31 44 52  6] [28 30 32 36 58  6] [] [6] 6.0
[ 3 13 28 38 63 14] [19 25 43 46 48 14] [] [14] 6.0
[ 1 15 21 32 46  1] [ 7 10 16 46 56  1] [46] [1] 7.0
[ 8 12 25 41 64  5] [ 2 12 32 50 65  5] [12] [5] 7.0
-----> Accuracy: 4.3333 | Match Score: 32.0 <------
----- 3 ------
[ 3 24 30 42 56  7] [22 39 43 62 64  7] [] [7] 6.0
[11 12 15 16 54 18] [ 4  6 16 30 56 18] [16] [18] 7.0
[ 1  2 24 38 57 14] [19 25 43 46 48 14] [] [14] 6.0
[ 1 12 21 32 46  1] [ 7 10 16 46 56  1] [46] [1] 7.0
[ 8 

In [ ]:
print('-----> Winner is ' + str(int(winningState)) + ' with ' + str(int(winningScore)) + ' <------')
# Fitting KNN
neigh = KNeighborsClassifier(weights=KNNWeights, algorithm=KNNAlgorithm, n_neighbors=int(winningState))
neigh.fit(X_fit, y)

# Predicting the next draw set results
nextdraw_n_pred = neigh.predict([nextdraw_set])
print(nextdraw_n_pred[0], nextdraw_set)

nextDrawResults.append([{"numbers":nextdraw_n_pred[0]},{"score":int(winningScore)},{"class":"weather - KNeighborsClassifier - U"}])

-----> Winner is 121 with 50 <------
[ 1 28 36 59 68 11] [29.97, 74.8, 86.84, 81, 81.06, 2]


# KNN Classifier - distance

In [ ]:
winningScore = 0
winningState = 0

in_neighbors = 1
while in_neighbors <= 154:
    # Fitting KNN
    KNNWeights = "distance" # weights{"uniform", "distance"}
    KNNAlgorithm = "auto" # algorithm{"auto", "ball_tree", "kd_tree", "brute"}
    neigh = KNeighborsClassifier(weights=KNNWeights, algorithm=KNNAlgorithm, n_neighbors=in_neighbors)
    neigh.fit(X_fit_train, y_train)

    # Predicting the Test set results
    y_n_pred = neigh.predict(X_fit_test)
    
    print('----- ' + str(in_neighbors) + ' ------')
    accuracyScore = 0
    totalMatchScore = 0
    for index, pred in enumerate(y_n_pred):
        accuracy = accuracy_score(y_test[index], pred)
        accuracyScore += accuracy
        comparePOS = list(set(pred[:5]) & set(y_test[index][:5]))
        comparePWB = list(set(pred[5:]) & set(y_test[index][5:]))
        matchScore = predictionScore(pred[:5], y_test[index][:5]) + (predictionScore(pred[5:], y_test[index][5:])*6)
        if matchScore >= 6:
            totalMatchScore += matchScore
            print(pred, y_test[index], comparePOS, comparePWB, matchScore)
        # Find the winner!
        if totalMatchScore >= winningScore:
            winningScore = totalMatchScore
            winningState = in_neighbors
    print('-----> Accuracy: ' + str(round(accuracyScore,4)) + ' | Match Score: ' + str(totalMatchScore) + ' <------')

    in_neighbors += 1

----- 1 ------
[ 7 15 18 32 45 20] [10 30 51 57 63 20] [] [20] 6.0
[23 25 39 54 67 11] [ 4 39 48 50 51 11] [39] [11] 7.0
[19 28 43 67 69  7] [19 28 41 42 51  7] [19, 28] [7] 9.0
[ 3 43 45 61 65 14] [19 25 43 46 48 14] [43] [14] 7.0
[24 61 63 64 69 18] [ 5 21 36 61 62 18] [61] [18] 7.0
[ 1 15 21 32 46  1] [ 7 10 16 46 56  1] [46] [1] 7.0
[17 54 56 63 69 20] [ 3  7  9 31 33 20] [] [20] 6.0
-----> Accuracy: 3.8333 | Match Score: 49.0 <------
----- 2 ------
[ 7 15 18 32 45 20] [10 30 51 57 63 20] [] [20] 6.0
[23 25 39 54 67 11] [ 4 39 48 50 51 11] [39] [11] 7.0
[19 28 43 67 69  7] [19 28 41 42 51  7] [19, 28] [7] 9.0
[ 3 43 45 61 65 14] [19 25 43 46 48 14] [43] [14] 7.0
[24 61 63 64 69 18] [ 5 21 36 61 62 18] [61] [18] 7.0
[ 1 15 21 32 46  1] [ 7 10 16 46 56  1] [46] [1] 7.0
[17 54 56 63 69 20] [ 3  7  9 31 33 20] [] [20] 6.0
-----> Accuracy: 3.8333 | Match Score: 49.0 <------
----- 3 ------
[ 7 15 18 32 45 20] [10 30 51 57 63 20] [] [20] 6.0
[23 25 39 54 67 11] [ 4 39 48 50 51 11] [39] [1

In [ ]:
print('-----> Winner is ' + str(int(winningState)) + ' with ' + str(int(winningScore)) + ' <------')
# Fitting KNN
neigh = KNeighborsClassifier(weights=KNNWeights, algorithm=KNNAlgorithm, n_neighbors=int(winningState))
neigh.fit(X_fit, y)

# Predicting the next draw set results
nextdraw_n_pred = neigh.predict([nextdraw_set])
print(nextdraw_n_pred[0], nextdraw_set)

nextDrawResults.append([{"numbers":nextdraw_n_pred[0]},{"score":int(winningScore)},{"class":"weather - KNeighborsClassifier - D"}])

-----> Winner is 3 with 49 <------
[19 23 32 35 68 21] [29.97, 74.8, 86.84, 81, 81.06, 2]


# MLPRegressor - lbfgs

In [ ]:
winningScore = 0
winningState = 0

in_randoms = 1
while in_randoms <= 104:
    # Fitting MLPC
    MLPCSolver = "lbfgs" # solver{"lbfgs", "sgd", "adam"}, default=’adam’
    MLPclf = MLPRegressor(hidden_layer_sizes=(4,4), max_iter=1536, alpha=0.0001,  verbose=10,
                           solver=MLPCSolver, random_state=in_randoms, tol=0.000000001)
    MLPclf.fit(X_train, y_train)

    # Predicting the Test set results
    y_r_pred = MLPclf.predict(X_test)

    totalMatchScore = 0
    print('----- ' + str(in_randoms) + ' ------ ')
    for index, pred in enumerate(y_r_pred):
        pred = list(map(round, pred))
        comparePOS = list(set(pred[:5]) & set(y_test[index][:5]))
        comparePWB = list(set(pred[5:]) & set(y_test[index][5:]))
        matchScore = predictionScore(pred[:5], y_test[index][:5]) + (predictionScore(pred[5:], y_test[index][5:])*6)
        if matchScore >= 6:
            totalMatchScore += matchScore
            print(pred, y_test[index], comparePOS, comparePWB, matchScore)#, round(accuracy,3), X_test[index])
        # Find the winner!
        if totalMatchScore >= winningScore:
            winningScore = totalMatchScore
            winningState = in_randoms
    print('-----> Match Score: ' + str(totalMatchScore) + ' <------')

    in_randoms += 1

----- 1 ------ 
[12, 24, 35, 47, 58, 14] [16 25 36 44 55 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [ 8 40 49 58 63 14] [58] [14] 7.0
[12, 24, 35, 47, 58, 14] [19 25 43 46 48 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [ 5  8 17 27 28 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [ 5  6 45 55 59 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [19 31 35 50 67 14] [35] [14] 7.0
-----> Match Score: 38.0 <------
----- 2 ------ 
[12, 24, 35, 47, 58, 14] [16 25 36 44 55 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [ 8 40 49 58 63 14] [58] [14] 7.0
[12, 24, 35, 47, 58, 14] [19 25 43 46 48 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [ 5  8 17 27 28 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [ 5  6 45 55 59 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [19 31 35 50 67 14] [35] [14] 7.0
-----> Match Score: 38.0 <------
----- 3 ------ 
[12, 24, 35, 47, 58, 14] [16 25 36 44 55 14] [] [14] 6.0
[12, 24, 35, 47, 58, 14] [ 8 40 49 58 63 14] [58] [14] 7.0
[12, 24, 35, 47, 58, 14] [19 25 43 46 48 14] [] [14] 6.0
[12, 24, 35, 47, 58, 

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


----- 93 ------ 
[12, 23, 34, 46, 56, 13] [27 32 34 43 52 13] [34] [13] 7.0
[12, 24, 35, 48, 59, 14] [16 25 36 44 55 14] [] [14] 6.0
[12, 24, 36, 48, 59, 14] [ 8 40 49 58 63 14] [] [14] 6.0
[12, 24, 36, 48, 59, 14] [19 25 43 46 48 14] [48] [14] 7.0
[12, 23, 34, 46, 57, 13] [ 8 23 37 52 63 13] [23] [13] 7.0
[12, 23, 35, 47, 58, 13] [ 2 23 40 59 69 13] [23] [13] 7.0
[12, 24, 36, 48, 59, 14] [19 31 35 50 67 14] [] [14] 6.0
-----> Match Score: 46.0 <------
----- 94 ------ 
[11, 22, 33, 45, 57, 13] [12 33 54 57 60 13] [33, 57] [13] 9.0
[12, 23, 34, 46, 58, 13] [27 32 34 43 52 13] [34] [13] 7.0
[13, 25, 37, 49, 59, 14] [16 25 36 44 55 14] [25] [14] 7.0
[13, 24, 37, 49, 59, 14] [ 8 40 49 58 63 14] [49] [14] 7.0
[12, 24, 35, 47, 58, 14] [19 25 43 46 48 14] [] [14] 6.0
[12, 23, 35, 47, 58, 13] [ 8 23 37 52 63 13] [23] [13] 7.0
[12, 24, 36, 48, 59, 14] [ 5  6 45 55 59 14] [59] [14] 7.0
-----> Match Score: 50.0 <------
----- 95 ------ 
[12, 24, 35, 47, 58, 14] [16 25 36 44 55 14] [] [14] 6.0
[12,

In [ ]:
print('-----> Winner is ' + str(int(winningState)) + ' with ' + str(int(winningScore)) + ' <------')
# Fitting RNC
MLPclf = MLPRegressor(hidden_layer_sizes=(4,4), max_iter=1536, alpha=0.0001,  verbose=10,
                           solver=MLPCSolver, random_state=int(winningState), tol=0.000000001)
MLPclf.fit(X, y)

# Predicting the next draw set results
nextdraw_MLpred = MLPclf.predict([nextdraw_set])
nextdraw_MLpred[0] = list(map(round, nextdraw_MLpred[0]))
print(nextdraw_MLpred[0], nextdraw_set)

nextDrawResults.append([{"numbers":list(map(round, nextdraw_MLpred[0]))},{"score":int(winningScore)},{"class":"weather - MLPRegressor - L"}])

-----> Winner is 101 with 62 <------
[12. 24. 36. 48. 60. 14.] [29.97, 74.8, 86.84, 81, 81.06, 2]


# MLPRegressor - sgd

In [ ]:
winningScore = 0
winningState = 0

in_randoms = 1
while in_randoms <= 104:
    # Fitting MLPC
    MLPCSolver = "sgd" # solver{"lbfgs", "sgd", "adam"}, default=’adam’
    MLPclf = MLPRegressor(hidden_layer_sizes=(4,4), max_iter=1536, alpha=0.0001,  verbose=10,
                           solver=MLPCSolver, random_state=in_randoms, tol=0.000000001)
    MLPclf.fit(X_train, y_train)

    # Predicting the Test set results
    y_r_pred = MLPclf.predict(X_test)

    totalMatchScore = 0
    print('----- ' + str(in_randoms) + ' ------ ')
    for index, pred in enumerate(y_r_pred):
        pred = list(map(round, pred))
        comparePOS = list(set(pred[:5]) & set(y_test[index][:5]))
        comparePWB = list(set(pred[5:]) & set(y_test[index][5:]))
        matchScore = predictionScore(pred[:5], y_test[index][:5]) + (predictionScore(pred[5:], y_test[index][5:])*6)
        if matchScore >= 6:
            totalMatchScore += matchScore
            print(pred, y_test[index], comparePOS, comparePWB, matchScore)#, round(accuracy,3), X_test[index])
        # Find the winner!
        if totalMatchScore >= winningScore:
            winningScore = totalMatchScore
            winningState = in_randoms
    print('-----> Match Score: ' + str(totalMatchScore) + ' <------')

    in_randoms += 1

Streaming output truncated to the last 5000 lines.
Iteration 194, loss = 60.98349086
Iteration 195, loss = 60.98316600
Iteration 196, loss = 60.98326786
Iteration 197, loss = 60.98294904
Iteration 198, loss = 60.98554822
Iteration 199, loss = 60.98276235
Iteration 200, loss = 60.98316598
Iteration 201, loss = 60.98273116
Iteration 202, loss = 60.98295140
Iteration 203, loss = 60.98254361
Iteration 204, loss = 60.98241354
Iteration 205, loss = 60.98291100
Iteration 206, loss = 60.98301739
Iteration 207, loss = 60.98278365
Iteration 208, loss = 60.98230240
Iteration 209, loss = 60.98235430
Iteration 210, loss = 60.98274019
Iteration 211, loss = 60.98307833
Iteration 212, loss = 60.98224058
Iteration 213, loss = 60.98213066
Iteration 214, loss = 60.98277400
Iteration 215, loss = 60.98189167
Iteration 216, loss = 60.98217713
Iteration 217, loss = 60.98196309
Iteration 218, loss = 60.98201934
Iteration 219, loss = 60.98239725
Iteration 220, loss = 60.98195054
Iteration 221, loss = 60.981819

In [ ]:
print('-----> Winner is ' + str(int(winningState)) + ' with ' + str(int(winningScore)) + ' <------')
# Fitting RNC
MLPclf = MLPRegressor(hidden_layer_sizes=(4,4), max_iter=1536, alpha=0.0001,  verbose=10,
                           solver=MLPCSolver, random_state=int(winningState), tol=0.000000001)
MLPclf.fit(X, y)

# Predicting the next draw set results
nextdraw_MLpred = MLPclf.predict([nextdraw_set])
nextdraw_MLpred[0] = list(map(round, nextdraw_MLpred[0]))
print(nextdraw_MLpred[0], nextdraw_set)

nextDrawResults.append([{"numbers":list(map(round, nextdraw_MLpred[0]))},{"score":int(winningScore)},{"class":"weather - MLPRegressor - S"}])

-----> Winner is 49 with 61 <------
Iteration 1, loss = 131207282.61903372
Iteration 2, loss = 10006928.36891563
Iteration 3, loss = 20500615.01322863
Iteration 4, loss = 29520859.18991382
Iteration 5, loss = 36357677.02730908
Iteration 6, loss = 41238277.94664849
Iteration 7, loss = 44610463.22429676
Iteration 8, loss = 46896188.62814995
Iteration 9, loss = 48428078.20833450
Iteration 10, loss = 49450446.27393344
Iteration 11, loss = 50125747.83796978
Iteration 12, loss = 50570592.48391920
Iteration 13, loss = 50863641.06017731
Training loss did not improve more than tol=0.000000 for 10 consecutive epochs. Stopping.
[-57. -72. -37. -17. -85. -95.] [29.97, 74.8, 86.84, 81, 81.06, 2]


# Show the results
Order the results by the best scores

In [ ]:
print("PB", nextdraw_date.strftime("%Y-%m-%d"))
#for predictions in nextDrawResults:
#    print(list(map(int, predictions[0]['numbers'])), predictions[1]['score'], predictions[2]['class'])
nextDrawResultsSorted = sorted(nextDrawResults, key=lambda k: k[1]['score'], reverse=True)
for predictions in nextDrawResultsSorted:
    print(list(map(int, predictions[0]['numbers'])), predictions[1]['score'], predictions[2]['class'])

PB 2022-08-24
[3, 17, 49, 58, 68, 8] 80 weather - RandomForestClassifier - E
[3, 25, 35, 58, 68, 10] 74 weather - RandomForestClassifier - G
[12, 24, 36, 48, 60, 14] 62 weather - MLPRegressor - L
[-57, -72, -37, -17, -85, -95] 61 weather - MLPRegressor - S
[1, 28, 36, 59, 68, 11] 50 weather - KNeighborsClassifier - U
[19, 23, 32, 35, 68, 21] 49 weather - KNeighborsClassifier - D


# Write Top Pick to Date

In [ ]:
# write the top pick numbers back to the date record for display
#print(str(nextDrawResultsSorted[0][0]['numbers']))
DBentry = LuckyWeatherNumbers.update_item(
    Key = { 
        'draw_date': str(datetime.date(nextdraw_date)),
        'night': str(datetime.date(nextdraw_date).weekday())
    },
    UpdateExpression = 'SET top_pick = :this_top_pick',
    ExpressionAttributeValues = {
        ':this_top_pick': str(nextDrawResultsSorted[0][0]['numbers'])
    }
) 

print(str(datetime.date(nextdraw_date)), nextDrawResultsSorted[0][0]['numbers'], DBentry['ResponseMetadata']['RequestId'])

2022-08-24 [3, 17, 49, 58, 68, 8] 8HLS8KBF4KV9OLL9NKE4I9NENJVV4KQNSO5AEMVJF66Q9ASUAAJG


In [ ]:
# display results
table = dynamodb.Table('LuckyWeatherNumbers')
#print(table.creation_date_time)

# grab all the records...
response = table.scan(
    FilterExpression=Attr('top_pick').exists(),
    ProjectionExpression='draw_date, POS1, POS2, POS3, POS4, POS5, PWRB, night, top_pick'
)
# put them in a dataframe
df_w = pd.DataFrame(response['Items'])

# make everything numeric
for column in df_w:
    # set all to numeric
    #print(column)
    if column not in ['draw_date', 'top_pick']:
      df_w[column] = pd.to_numeric(df_w[column], errors='coerce')


# re-sort the columns
df_w = df_w[['draw_date', 'top_pick', 'POS1', 'POS2', 'POS3', 'POS4', 'POS5', 'PWRB', 'night']]

#print('Shape of the dataset: ' + str(df_w.shape))
df_w.head()

KeyError: ignored